[package]
name = "strata-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mupdf.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
log.workspace = true
lru = "0.18"
ttf-parser = "0.25"
memmap2 = "0.9"
mupdf-sys = { version = "0.8", default-features = false }
unicode-normalization = "0.1"
strata-ocr = { version = "0.1.0", path = "../strata-ocr" }
image = { version = "0.25", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "6"
math-core = "0.8"

[build-dependencies]
cc = "1"

[dev-dependencies]
strata-ocr = { path = "../strata-ocr" }
